### ISSUE TITLE
Add Codeforces Problem Solutions

### ISSUE THREAD

**Issue by ighosh98** [ighosh98/Competitive-Coding-Solutions#6]
- [ ] Contests should have occurred in the Month of September or October in the Year 2020.

**Comment by guptaa98** [comment]
I would like to work on this.

**Comment by princekalra** [comment]
hey can i work on this

**Comment by ighosh98** [comment]
Closing this for the time being. Need to update the rules for PRs to avoid spams. If you have already started working by adding a comment earlier, please continue working on it.
